POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlplcmdpbzIwMGlzbSIsImlkIjoiNjgwNTU5YjY3NDlhNGQxNWIzMWVhOTc5IiwiaWF0IjoxNzQ1MjUyMDIyfQ.7QjLAwZwGpEsUbzbIVK4Pl_KPDuTMtv7d-iBr4h8hMk

{
  "content": "Contenido aleatorio",
  "important": true,
  "userId":"680559b6749a4d15b31ea979"
}